name: ecomerce
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.2
  material_design_icons_flutter: ^6.0.7096
  google_fonts: ^3.0.1
  mobx: ^2.1.3+1
  flutter_mobx: ^2.0.6+5
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  dio: ^4.0.6
  flutter_spinkit: ^5.1.0
  basic_utils: ^5.4.2
  equatable: ^2.0.5
  dartz: ^0.10.1
  simple_animations: ^5.0.0+3
  get_it: ^7.2.0
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  lottie: ^2.2.0
  liquid_pull_to_refresh: ^3.0.1

dev_dependencies:
  build_runner: ^2.3.3
  mobx_codegen: ^2.1.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/img/

  